
### Add Deployments ### 
POST http://localhost:3000/api/deployment/add/deployment
Content-Type: application/json

{
      "name": "test template 3",
      "url": "https://ejam-backend-server.herokuapp.com/api/test3",
      "versions": "1.0.3"
}

### get deployments ### 
GET http://localhost:3000/api/deployment/get/deployments
Content-Type: application/json


### Delete Deployment ### 
DELETE http://localhost:3000/api/deployment/delete/deployments
Content-Type: application/json

{
      "deployment_id": "61319d22ab6cf62d60949b3a"
}