
### Add Deployments ### 
POST http://localhost:3000/api/deployment/add/deployment
Content-Type: application/json

{
      "name": "React Hooks",
      "versions": "16.0.1",
      "url": "https://react.org/reactHooks/"
}

### get deployments ### 
GET http://localhost:3000/api/deployment/get/deployments
Content-Type: application/json


### Delete Deployment ### 
DELETE http://localhost:3000/api/deployment/delete/deployments
Content-Type: application/json

{
      "deployment_id": "6132d67433dd3250f80cc73f"
}